apiVersion: apps/v1
kind: Deployment
metadata:
  name: executive-team
  namespace: elf-automations
  labels:
    app: executive-team
    team: executive
    framework: crewai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: executive-team
  template:
    metadata:
      labels:
        app: executive-team
        team: executive
        framework: crewai
    spec:
      containers:
      - name: executive-team
        image: elf-automations/executive-team:latest
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-keys
              key: openai-api-key
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: executive-team-service
  namespace: elf-automations
  labels:
    app: executive-team
spec:
  selector:
    app: executive-team
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: executive-team-config
  namespace: elf-automations
data:
  team_name: "executive-team"
  department: "executive"
  framework: "crewai"
  process_type: "hierarchical"