# Secrets template - create these before deployment
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: elf-teams
type: Opaque
stringData:
  uri: "bolt://neo4j:7687"
  username: "neo4j"
  password: "your-neo4j-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: qdrant-credentials
  namespace: elf-teams
type: Opaque
stringData:
  url: "http://qdrant:6333"
  api_key: "your-qdrant-api-key"  # Optional
