apiVersion: v1
kind: Service
metadata:
  name: rag-processor-team
  namespace: elf-teams
  labels:
    app: rag-processor-team
spec:
  selector:
    app: rag-processor-team
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
