# Template for A2A Gateway secrets
# Copy this file to secret.yaml and fill in the base64-encoded values
#
# To encode a value: echo -n "your-value" | base64
#
apiVersion: v1
kind: Secret
metadata:
  name: a2a-gateway-secrets
  namespace: elf-teams
  labels:
    app: a2a-gateway
    component: gateway
type: Opaque
data:
  # Generate a secure token for team registration
  # Example: openssl rand -hex 32 | base64
  registration-token: <BASE64_ENCODED_REGISTRATION_TOKEN>
  
---
# Note: The supabase-credentials secret should already exist in the namespace
# If not, create it with:
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: supabase-credentials
#   namespace: elf-teams
# type: Opaque
# data:
#   url: <BASE64_ENCODED_SUPABASE_URL>
#   anon-key: <BASE64_ENCODED_SUPABASE_ANON_KEY>