apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: elf-infrastructure
  labels:
    app: neo4j
    component: database
data:
  neo4j.conf: |
    # Neo4j configuration for ElfAutomations

    # Network settings
    server.default_listen_address=0.0.0.0
    server.bolt.enabled=true
    server.bolt.listen_address=0.0.0.0:7687
    server.http.enabled=true
    server.http.listen_address=0.0.0.0:7474

    # Memory settings (adjust based on your resources)
    server.memory.heap.initial_size=1G
    server.memory.heap.max_size=2G
    server.memory.pagecache.size=1G

    # Query settings
    db.tx_timeout=30s
    dbms.transaction.timeout=30s

    # Security settings
    dbms.security.auth_enabled=true
    dbms.security.procedures.unrestricted=apoc.*,gds.*

    # Logging
    server.logs.debug.enabled=false

    # Multi-tenancy support
    dbms.multi_database=true

    # Enable APOC procedures
    dbms.security.procedures.allowlist=apoc.*,gds.*

    # Enable full-text search
    dbms.index.fulltext.enabled=true
