apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: elf-infrastructure
  labels:
    app: neo4j
    component: database
type: Opaque
stringData:
  # Default credentials - CHANGE THESE IN PRODUCTION!
  NEO4J_AUTH: "neo4j/elfautomations2025"  # username/password
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "elfautomations2025"
