# Optional: NodePort service for external access during development
apiVersion: v1
kind: Service
metadata:
  name: neo4j-external
  namespace: elf-infrastructure
  labels:
    app: neo4j
    component: database
spec:
  type: NodePort
  selector:
    app: neo4j
    component: database
  ports:
  - name: http
    port: 7474
    targetPort: 7474
    protocol: TCP
    nodePort: 30474  # Access Neo4j browser at <node-ip>:30474
  - name: bolt
    port: 7687
    targetPort: 7687
    protocol: TCP
    nodePort: 30687  # Bolt connection at <node-ip>:30687