version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "bryansparks"
    assignees:
      - "bryansparks"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # Web dependencies
  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bryansparks"
    commit-message:
      prefix: "deps(web)"
    labels:
      - "dependencies"
      - "web"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bryansparks"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker/agents"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bryansparks"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bryansparks"
    commit-message:
      prefix: "deps(actions)"
    labels:
      - "dependencies"
      - "github-actions"
