[package]
name = "agent-xds"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"

[lib]
path = "src/lib.rs"

[build-dependencies]
anyhow.workspace = true
prost-build.workspace = true
tonic-build.workspace = true

[dependencies]
agent-core .workspace = true
anyhow.workspace = true
async-stream.workspace = true
prometheus-client.workspace = true
prost.workspace = true
prost-types.workspace = true
serde_json.workspace = true
split-iter.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
