apiVersion: v1
kind: Service
metadata:
  name: google-drive-watcher
  namespace: elf-mcps
  labels:
    app: google-drive-watcher
spec:
  selector:
    app: google-drive-watcher
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  type: ClusterIP
---
