apiVersion: v1
kind: Namespace
metadata:
  name: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: elf-automations
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "elf-n8n-2024"
  N8N_ENCRYPTION_KEY: "n8n-encryption-key-change-in-production"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
          name: http
        env:
        - name: N8N_HOST
          value: "0.0.0.0"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: NODE_ENV
          value: "production"
        - name: WEBHOOK_URL
          value: "http://n8n.n8n.svc.cluster.local:5678/"
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        envFrom:
        - secretRef:
            name: n8n-secrets
        volumeMounts:
        - name: data
          mountPath: /home/node/.n8n
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  type: ClusterIP
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: n8n
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-external
  namespace: n8n
  labels:
    app: n8n
spec:
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
    name: http
    nodePort: 30678
  selector:
    app: n8n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-auto-deploy-test
  namespace: n8n
  labels:
    app: n8n
    test: gitops-auto-sync
data:
  timestamp: "2025-06-17 21:04:00"
  message: |
    This ConfigMap was automatically deployed by ArgoCD!
    No manual intervention required - just git push!
