apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elf-teams

resources:
  - persistent-volume-claims.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: n8n
  component: workflow-automation
  managed-by: kustomize
