apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: elf-teams
  labels:
    app: n8n
    component: workflow-automation
type: Opaque
stringData:
  # IMPORTANT: Replace these with your actual passwords before applying
  # You can generate base64 encoded values with: echo -n "your-password" | base64
  basic-auth-password: "ChangeThisStrongPassword123!"
  postgres-password: "ChangeThisPostgresPassword456!"