apiVersion: kagent.dev/v1alpha1
kind: Team
metadata:
  name: chief-ai-agent
  namespace: elf-automations
  labels:
    agent-type: distributed-crewai
    app: elf-automations
    component: team
    department: executive
    role: chief-executive-officer
    version: v1.0.0
spec:
  description: Team for Chief Executive Officer - Provide strategic leadership, coordinate
    departments, optimize company performance, and ensure business objectives are
    met across all divisions
  maxTurns: 10
  modelConfig: default-model-config
  participants:
  - chief-ai-agent
  roundRobinTeamConfig: {}
  terminationCondition:
    maxMessageTermination:
      maxMessages: 20
