apiVersion: kagent.dev/v1alpha1
kind: Team
metadata:
  name: sales-representative
  namespace: elf-automations
  labels:
    agent-type: distributed-crewai
    app: elf-automations
    component: team
    department: sales
    role: sales-representative
    version: v1.0.0
spec:
  description: Team for Sales Representative - Close deals, manage customer relationships,
    conduct product demonstrations, and achieve individual sales quotas
  maxTurns: 10
  modelConfig: default-model-config
  participants:
  - sales-representative
  roundRobinTeamConfig: {}
  terminationCondition:
    maxMessageTermination:
      maxMessages: 20
