apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elf-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bryansparks/ELFAutomations.git
    targetRevision: HEAD
    path: k8s/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: elf-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
