apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This is the parent kustomization for all infrastructure components
# ArgoCD will use this to deploy all infrastructure

resources:
  - neo4j/
  # Future infrastructure components can be added here:
  # - qdrant/
  # - monitoring/
  # - logging/
  # - ingress/

# Common labels for all infrastructure
commonLabels:
  app.kubernetes.io/part-of: elf-infrastructure
  app.kubernetes.io/managed-by: argocd
