apiVersion: v1
kind: Secret
metadata:
  name: llm-api-keys
  namespace: elf-teams
type: Opaque
stringData:
  OPENAI_API_KEY: "your-openai-api-key-here"
  ANTHROPIC_API_KEY: "your-anthropic-api-key-here"
