apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway
  namespace: virtual-ai-platform
  labels:
    app: agentgateway
    component: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentgateway
  template:
    metadata:
      labels:
        app: agentgateway
        component: gateway
    spec:
      serviceAccountName: agentgateway-service-account
      containers:
      - name: agentgateway
        image: agentgateway/agentgateway:latest
        ports:
        - containerPort: 3000
          name: mcp
          protocol: TCP
        - containerPort: 8080
          name: admin
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: AGENTGATEWAY_CONFIG
          value: "/etc/agentgateway/config.json"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: anon-key
        - name: SUPABASE_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: personal-access-token
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: project-id
        - name: PROJECT_NAME
          value: "virtual-ai-company-platform"
        volumeMounts:
        - name: config
          mountPath: /etc/agentgateway
          readOnly: true
        - name: mcp-servers
          mountPath: /app/mcp_servers
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      - name: mcp-servers
        image: bryansparks/virtual-ai-agents:latest
        command: ["sleep", "infinity"]
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: anon-key
        - name: SUPABASE_PERSONAL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: personal-access-token
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: project-id
        - name: PROJECT_NAME
          value: "virtual-ai-company-platform"
        volumeMounts:
        - name: mcp-servers
          mountPath: /app/mcp_servers
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: config
        configMap:
          name: agentgateway-config
      - name: mcp-servers
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
