llm:
  provider: OpenAI
  model: gpt-4
  temperature: 0.7
  max_tokens: 4096
  fallback:
    enabled: true
    chain:
    - provider: OpenAI
      model: gpt-4
    - provider: OpenAI
      model: gpt-3.5-turbo
    - provider: Anthropic
      model: claude-3-opus-20240229
    - provider: Anthropic
      model: claude-3-sonnet-20240229
    - provider: Anthropic
      model: claude-3-haiku-20240307
  quota:
    enabled: true
    daily_limit: 10.0
    track_by_team: true
  retry:
    enabled: true
    max_attempts: 3
    backoff_factor: 2
  openai:
    api_key_env: OPENAI_API_KEY
    organization_env: OPENAI_ORG_ID
    base_url: null
