apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elf-automations

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: qdrant
      app.kubernetes.io/part-of: elf-automations
      app.kubernetes.io/component: vector-database