apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: elf-automations
  labels:
    app: qdrant
    component: vector-db
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6333
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 6334
    targetPort: grpc
    protocol: TCP
  selector:
    app: qdrant