apiVersion: apps/v1
kind: Deployment
metadata:
  name: chief-ai-agent-standalone
  namespace: elf-automations
  labels:
    app: chief-ai-agent
    component: agent
    department: executive
    agent-type: distributed-crewai
    role: chief-executive-officer
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chief-ai-agent
      component: agent
  template:
    metadata:
      labels:
        app: chief-ai-agent
        component: agent
        department: executive
        agent-type: distributed-crewai
        role: chief-executive-officer
    spec:
      containers:
      - name: chief-ai-agent
        image: elf-automations/chief-ai-agent:v2
        imagePullPolicy: Never
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
        ports:
        - containerPort: 8090
          name: a2a
        - containerPort: 8091
          name: health
        env:
        - name: AGENT_ID
          value: "chief-ai-agent"
        - name: AGENT_ROLE
          value: "Chief Executive Officer"
        - name: DEPARTMENT
          value: "executive"
        - name: A2A_PORT
          value: "8090"
        - name: A2A_HOST
          value: "0.0.0.0"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PYTHONPATH
          value: "/app"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai-api-key
        command: ["python", "/app/agents/distributed/run_chief_ai_standalone.py"]
        args: []
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8091
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: agent-data
          mountPath: /app/data
      volumes:
      - name: agent-data
        emptyDir: {}
      securityContext:
        fsGroup: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: chief-ai-agent-service
  namespace: elf-automations
  labels:
    app: chief-ai-agent
    component: agent
spec:
  selector:
    app: chief-ai-agent
    component: agent
  ports:
  - name: a2a
    port: 8090
    targetPort: 8090
    protocol: TCP
  - name: health
    port: 8091
    targetPort: 8091
    protocol: TCP
  type: ClusterIP
