apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: chief-ai-agent
  namespace: elf-automations
  labels:
    department: executive
    role: chief-executive-officer
    agent-type: distributed-crewai
    version: v1.0.0
spec:
  # Agent Configuration
  agentId: chief-ai-agent
  role: "Chief Executive Officer"
  goal: "Provide strategic leadership, coordinate departments, optimize company performance, and ensure business objectives are met across all divisions"
  backstory: "You are the Chief AI Agent, the executive leader of a Virtual AI Company Platform. You have extensive experience in strategic planning, organizational leadership, and business optimization."
  department: executive

  # Container Configuration
  image: elf-automations/distributed-agent:latest
  imagePullPolicy: Always

  # Resource Requirements
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Scaling Configuration
  replicas: 1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

  # A2A Communication Configuration
  a2a:
    enabled: true
    port: 8090
    host: "0.0.0.0"
    discoveryEndpoint: "http://a2a-discovery-service:8080"

  # Service Configuration
  service:
    name: chief-ai-agent-service
    type: ClusterIP
    ports:
      - name: a2a
        port: 8090
        targetPort: 8090
        protocol: TCP
      - name: health
        port: 8091
        targetPort: 8091
        protocol: TCP

  # Environment Variables
  env:
    - name: AGENT_ID
      value: "chief-ai-agent"
    - name: AGENT_ROLE
      value: "Chief Executive Officer"
    - name: DEPARTMENT
      value: "executive"
    - name: A2A_PORT
      value: "8090"
    - name: A2A_HOST
      value: "0.0.0.0"
    - name: LOG_LEVEL
      value: "INFO"
    - name: PYTHONPATH
      value: "/app"

  # Health Checks
  healthCheck:
    enabled: true
    httpGet:
      path: /health
      port: 8091
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  # Readiness Probe
  readinessProbe:
    httpGet:
      path: /ready
      port: 8091
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  # Agent Capabilities
  capabilities:
    - strategic_planning
    - performance_monitoring
    - resource_allocation
    - escalation_handling
    - cross_department_coordination
    - business_intelligence
    - decision_making
    - leadership_communication

  # Executive-specific Configuration
  executiveConfig:
    performanceReviewInterval: "1h"
    departmentAccess: "all"
    escalationAuthority: "full"
    resourceAllocationLimit: "unlimited"
    strategicPlanningScope: "company-wide"

  # Monitoring and Observability
  monitoring:
    enabled: true
    metrics:
      - decisions_made
      - escalations_handled
      - strategic_initiatives_launched
      - department_coordination_sessions
      - active_strategic_objectives
      - pending_escalations
    alerts:
      - name: high-escalation-volume
        condition: "escalations_handled > 10"
        severity: warning
      - name: strategic-objectives-stalled
        condition: "active_strategic_objectives == 0"
        severity: critical

  # Security Configuration
  security:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false

  # Volume Mounts (for persistent data if needed)
  volumes:
    - name: agent-data
      emptyDir: {}

  volumeMounts:
    - name: agent-data
      mountPath: /app/data

  # Networking
  networking:
    # Allow communication with all departments
    networkPolicy:
      enabled: true
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: elf-automations
          ports:
            - protocol: TCP
              port: 8090
      egress:
        - to: []  # Allow all outbound traffic for executive coordination

  # Startup Command
  command: ["python", "-m", "agents.distributed.examples.chief_ai_agent"]

  # Annotations for additional metadata
  annotations:
    description: "Chief AI Agent - Executive leadership for distributed agent architecture"
    version: "1.0.0"
    maintainer: "ELF Automations"
    last-updated: "2024-06-04"
    agent-tier: "executive"
    criticality: "high"
