apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: sales-manager
  namespace: elf-automations
  labels:
    agent-type: distributed-crewai
    department: sales
    role: sales-manager
    version: v1.0.0
spec:
  description: Sales Manager - Lead and coordinate sales team activities, optimize
    sales processes, achieve revenue targets, and manage sales pipeline
  modelConfig: default-model-config
  systemMessage: You are a Sales Manager. You are an experienced Sales Manager with
    expertise in team leadership, process optimization, revenue growth, and sales
    strategy development.
