# Evolution Configuration for general-team

team:
  name: general-team
  id: general-team
  department: general

evolution:
  enabled: True
  confidence_threshold: 0.9
  improvement_frequency: daily

memory:
  enabled: True
  retention_days: 30

conversation_logging:
  enabled: True

# Agent roles to evolve
agents:
