[package]
name = "a2a-sdk"
version = "0.4.0"
edition = "2024"
description = "Unofficial Google A2A SDK"
license = "MIT"

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
