apiVersion: v1
kind: Secret
metadata:
  name: elf-credentials
  namespace: elf-teams
type: Opaque
stringData:
  # These values will be populated by the credential manager
  # DO NOT hardcode values here!
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  SUPABASE_URL: "${SUPABASE_URL}"
  SUPABASE_KEY: "${SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_KEY: "${SUPABASE_SERVICE_KEY}"
---
# Team-specific secrets will be generated automatically
# by the credential management system
