apiVersion: apps/v1
kind: Deployment
metadata:
  name: kagent-controller
  namespace: elf-automations
  labels:
    app: kagent
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kagent
      component: controller
  template:
    metadata:
      labels:
        app: kagent
        component: controller
    spec:
      serviceAccountName: kagent-controller
      containers:
      - name: controller
        image: kagent/kagent:latest
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 9443
          name: webhook
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kagent-controller
  namespace: elf-automations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kagent-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["kagent.dev"]
  resources: ["agents", "agentgroups"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kagent-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kagent-controller
subjects:
- kind: ServiceAccount
  name: kagent-controller
  namespace: elf-automations
---
apiVersion: v1
kind: Service
metadata:
  name: kagent-controller
  namespace: elf-automations
  labels:
    app: kagent
    component: controller
spec:
  selector:
    app: kagent
    component: controller
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: webhook
    port: 9443
    targetPort: 9443
