team:
  name: general-team
  purpose: Executive leadership team with CEO, CTO, CMO, CFO
  department: general
  framework: CrewAI
  reporting_to: null
  members:
  - name: ceo
    role: Chief Executive Officer
    responsibilities: []
    skills: []
    personality: visionary
    is_manager: true
    manages_teams: []
  - name: cto
    role: Chief Technology Officer
    responsibilities: []
    skills: []
    personality: analytical
    is_manager: false
    manages_teams: []
  - name: cmo
    role: Chief Marketing Officer
    responsibilities: []
    skills: []
    personality: creative
    is_manager: false
    manages_teams: []
  - name: coo
    role: Chief Operating Officer
    responsibilities: []
    skills: []
    personality: pragmatic
    is_manager: false
    manages_teams: []
  - name: cfo
    role: Chief Financial Officer
    responsibilities: []
    skills: []
    personality: detail_oriented
    is_manager: false
    manages_teams: []
  - name: cpo
    role: Chief Product Officer
    responsibilities:
    - Ultimately owns all products in terms of features, user experience, and function.
      Works closely with the CTO on architecture and very closely with Engineering
      Management.
    skills: []
    personality: collaborator
    is_manager: false
    manages_teams: []
  communication:
    internal:
      style: natural_language
      logging:
        enabled: true
        format: conversation
        path: logs/general-team_communications.log
    external:
      protocol: a2a
      manager_only: true
      logging:
        enabled: true
        format: structured
        path: logs/general-team_a2a.log
  workflow:
    type: hierarchical
    manager: Chief Executive Officer
    delegation_enabled: false
  memory:
    enabled: true
    provider: qdrant
    continuous_learning: true
    experience_replay: true
  monitoring:
    metrics:
      enabled: true
      prometheus_port: 9090
    health_check:
      enabled: true
      endpoint: /health
      interval: 30
    logging:
      level: INFO
      format: json
      separate_files: true
