apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.kagent.io
spec:
  group: kagent.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              department:
                type: string
                enum: ["executive", "sales", "marketing", "product", "customer-success", "back-office"]
              role:
                type: string
              llmConfig:
                type: object
                properties:
                  provider:
                    type: string
                    enum: ["anthropic", "openai", "azure"]
                  model:
                    type: string
                  apiKey:
                    type: string
                  temperature:
                    type: number
                    minimum: 0
                    maximum: 2
              mcpServers:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    endpoint:
                      type: string
                    tools:
                      type: array
                      items:
                        type: string
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      memory:
                        type: string
                      cpu:
                        type: string
                  limits:
                    type: object
                    properties:
                      memory:
                        type: string
                      cpu:
                        type: string
              replicas:
                type: integer
                minimum: 1
                maximum: 10
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                  minReplicas:
                    type: integer
                  maxReplicas:
                    type: integer
                  targetCPUUtilizationPercentage:
                    type: integer
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Succeeded"]
              replicas:
                type: integer
              readyReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: agents
    singular: agent
    kind: Agent
    shortNames:
    - ag
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.kagent.io
spec:
  group: kagent.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              trigger:
                type: object
                properties:
                  type:
                    type: string
                    enum: ["cron", "event", "manual"]
                  schedule:
                    type: string
                  eventType:
                    type: string
              steps:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    agent:
                      type: string
                    action:
                      type: string
                    parameters:
                      type: object
                    dependencies:
                      type: array
                      items:
                        type: string
          status:
            type: object
            properties:
              phase:
                type: string
              startTime:
                type: string
              completionTime:
                type: string
              steps:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    status:
                      type: string
                    startTime:
                      type: string
                    completionTime:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: workflows
    singular: workflow
    kind: Workflow
    shortNames:
    - wf
