apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: elf-infrastructure
  labels:
    app: neo4j
    component: database
spec:
  type: ClusterIP
  selector:
    app: neo4j
    component: database
  ports:
  - name: http
    port: 7474
    targetPort: 7474
    protocol: TCP
  - name: bolt
    port: 7687
    targetPort: 7687
    protocol: TCP
