# A2A Configuration for Product Team
# Defines how this team communicates with other teams

team_id: product-team
manager: senior_product_manager

# Teams this team can communicate with
authorized_teams:
  - executive-team
  - engineering-team
  - marketing-team
  - sales-team
  - customer-success-team

# A2A endpoints this team exposes
capabilities:
  - name: create_prd
    description: "Create a Product Requirements Document"
    input_schema:
      type: object
      properties:
        description:
          type: string
          description: "Product description"
        context:
          type: object
          description: "Additional context (target users, features, constraints)"
      required: ["description"]
    output_schema:
      type: object
      properties:
        prd:
          type: object
          description: "Complete PRD document"
        status:
          type: string

  - name: market_research
    description: "Conduct market research for a product idea"
    input_schema:
      type: object
      properties:
        market:
          type: string
        competitors:
          type: array
          items:
            type: string

  - name: feature_prioritization
    description: "Prioritize features using RICE or other frameworks"
    input_schema:
      type: object
      properties:
        features:
          type: array
          items:
            type: object

# Message handling configuration
message_handling:
  timeout_seconds: 3600  # 1 hour for complex PRD creation
  retry_policy:
    max_retries: 2
    backoff_seconds: 60

# Logging configuration
logging:
  level: INFO
  structured_format: true
  include_message_content: true
